### ISSUE TITLE
Change server request query params, cookie params, and parsed body to return vec<(string, string)>

### ISSUE THREAD

**Issue by azjezz** [hhvm/hack-http-request-response-interfaces#39]
closes #36

**Comment by azjezz** [comment]
to stay consistent with getHeaders(), getUploadedFiles(), i think we should keep everything `KeyedContainer<string, string>`

**Comment by fredemmott** [comment]
*`Container<(string, string)>` should probably be used for these *and* `getHeaders()` - duplicates are OK

**Comment by azjezz** [comment]
`getHeaders()` is `KeyedContainer<string, Container<string>>` now ( `dict<string, vec<string>>` here ), which allows duplicates :)
